name: demo-crm-deployment
appName: demo-crm

replicaCount: 1

secretName: mongo-uri-secret


ingressService:
  name: ingress
  host: hodesay.bounceme.net #host name for ingress 
  pathType: Prefix
  tls:
    hosts:
    - hodesay.bounceme.net

publicPort: 8089

httpIngressClass: nginx
cert:
  config:
    email: michaelappiah2018@icloud.com
    tls:
      enabled: false
  clusterIssuerName: "letsencrypt-staging" 

serviceCluster:
  enabled: true #toggle to use clusterIP AND ingressControllers or LoadBalancer service


mongodb:
  replicaCount: 2
  port: 27017
  replicaSetName: MainRepSet
  arbiter:
    enabled: false
  persistence:
    name: mongodb-persistent-storage-claim
    size: 1Gi
    mountPath: /data/db
  podDisruptionBudget: {}
  auth:
    enabled: true
    existingSecret: mysecret
    rootUser: root
  architecture: replicaset
  podSecurityContext:
    enabled: true
    runAsUser: 999
    fsGroup: 999
    runAsNonRoot: true
    