apiVersion: v1
kind: Secret
metadata:
  name: mongo-uri-secret-prod
  namespace: prod
type: Opaque
data:
  uri: bW9uZ29kYjovL3Jvb3Q6ZGFtc2Vsb3BlbDY0NTc4NEBkZW1vLWNybS1tb25nb2RiLWhlYWRsZXNzLnByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvP3JlcGxpY2FTZXQ9TWFpblJlcFNldA==