apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-crm
  namespace: argocd
spec:
  project: on-staging

  source:
    repoURL: git@github.com:Terre8055/demo-crm-argocd.git
    targetRevision: HEAD
    path: app/
    helm:
      valueFiles:
        - "values-staging.yaml"
  destination: 
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true