apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-crm-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:Terre8055/demo-crm.git
    targetRevision: HEAD
    path: app/
    helm:
      valueFiles:
        - "values-prod.yaml"
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true