apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      charts:
        - chart: elastic
          releaseName: my-elastic
          version: 8.5.1
        - chart: kibana
          releaseName: my-kibana
          version: 8.5.1
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-crm-logging

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
