apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: kibana
    helm:
      releaseName: my-kibana
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-crm-logging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  podSpecPatch: |-
    spec:
      containers:
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
