name: demo-crm-deployment
appName: demo-crm-prod

replicaCount: 2

secretName: mongo-uri-secret-prod

ingressService:
  name: ingress
  host: hodesay.onthewifi.com #host name for ingress 
  pathType: Prefix
  tls:
    hosts:
    - hodesay.onthewifi.com

publicPort: 8089

httpIngressClass: nginx
cert:
  config:
    email: michaelappiah2018@icloud.com
    tls:
      enabled: true
  clusterIssuerName: "letsencrypt-prod" 

serviceCluster:
  enabled: true #toggle to use clusterIP AND ingressControllers or LoadBalancer service


mongodb:
  replicaCount: 3
  port: 27017
  replicaSetName: MainRepSet
  arbiter:
    enabled: false
  persistence:
    name: mongodb-persistent-storage-claim
    size: 1Gi
    mountPath: /data/db
  podDisruptionBudget: {}
  auth:
    enabled: true
    existingSecret: mysecret-prod
    rootUser: root
  architecture: replicaset
  podSecurityContext:
    enabled: true
    runAsUser: 999
    fsGroup: 999
    runAsNonRoot: true
    