apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-uri-secret
  namespace: staging
spec:
  encryptedData:
    uri: AgCqOtRLd7U+pDND20LfVOtMtrn5C/R/S5JQnjms/Kf+bIrobAQP2RnoYZ9WA7hj5MQnK00iuI3xKh7eWZcq6daoHEa0T6acKsuXCIpfWVWXB1ljhkA2WVfcRGVmYOqDaw2VDBadvOfoS/90VCP/4Fwsl1aEzeoV2XSMf+Ez80+myjl4r2r9UvBdd2x64vTbelPKS7zLffFHrqDmKocjm5jrMzgT/YqTDzgoX8eJoohKtHYDcya22YID0Lmcabgv80Z7sR9DmTVPaixaNLdLYOoaXSlFtsiz8v3kPeStq9tUEfQXhGrMYlHCpY04MmaOgJ4XLnPsNIk7+ptNV7Dl53R9yS8Cox6Mb65f48ew/gg9685uo21BtxNc0V+fQ0LzniwJpSRs2DutDjhdzIaiSN/84K8gc7HeIOYKWOzgFvKqBp+B7DJsxzc4Ky46eFrksKwym4S1uELuSdjflp4hvZkwALhYVJSuHTuqIYXIUwCyVs194alRO+0k2CcgGYgnue8Zspj6bD2Xs2EoNiflxrVDDcDI8pKShGEuV877uHltbIlLlHJDr+3MV/9QQ52CRWtCD+oq7VPi0pZIz+BichpzcCpUew9/pzqSOj85tw18SZG3zMYhzSo6ytI72uaBAirJs+yFacshoSRbvOQcCn6ci4hQNAmQKhPNlXDTEUv/F2hGRy2VAM+HofGghRUigLVCpYKiAgqNplTIRdS61Yz/lLwBa2sCeHpS8w2OsC9Mwz47pyCv6wxmwvih3N60NSFAgq1m53+9+mQlFJq/p1cwtCIXi43fd4cClKmhtBLWNgruzpm+qL/Yi0ggLD2okcrSOUp6THWz6nAx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-uri-secret
      namespace: staging
    type: Opaque

