apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: sealed-secret-application
spec:
  encryptedData:
    mongodb-replica-set-key: AgAwC1IoMDCekj0gnbTxYBR5jzs4Z3QSSfR8OfBfDBIrakkVEBoPLIh7H4YAxEjCJfmlHDsXzcdim3BWZfxIUIuBuswVV0lj8f8pVFaQzHJ8PwiG79LC29mlTByeH3XUD6YkjFFkkPGFPrjEmETFzHXiSGjZzNEE4xCN8+ldn7319kfUYrgH0z8kAYrgNdeF5QPLcvE3jpotf14bb+97KsQIFetuM1VA5LWpEfSeuH6wro6AlevjfW7Bp5NbvJWXnhII0kBBDE88iJWMVbQtSsvuzZh4Mu1kWxv3xJEFa9qt2RN4iwBoNeBkdBwWhNT61fB7lrmWHQAdRH67wIVVJhp2noofzrwdw0g+NTQbkjyuaSie/hSPn2NxWeoqed1o3A3DiaGS/bkjet7TBokggoCY+T4MPOVzZBJapFbQ4c62l9KK4jWaZHvK44zv3X4hmeA5r4r8qZGs+rcUEfPG6TKG82VbSuSvvwiXYn59DKBN8wrAvU83idVV2O4oojLfoRTNNhEYVbi2MZLDLqtGKghQfeBGSPf1+QoUzNvz/pSv2/rLRQdoNrXOANat5cu5eYf/JL/H5KgsKPXQGQm3GpmcN1M+PRPxL6BBKcJM6Cl1WtFu/OMkhzu7IU5Q5a8sYB6RMEKA0HwJyP7EJghPn/HWJw+HJ1pTjMPmhBPNySMMc7sFuLDWf6httNqsJgg/v6lxImeiiUWIqYWm
    mongodb-root-password: AgCUydKTAOqc1BdIOsDR+vsiR1An0NW7OYVrsv8+ohXCbeQWWIch/5bAvG1XiE4RTrLDMb7SVJGj2DP3X67YfBfUHpqmDc8HEIFoHpniHc6dUFMlL3LlY9xrEeu24p8cPBJwzNoWIK4wRoWst2xZxJY7m/KAljsf+2u6by7QcyH9577OQBkXX21wet48D6xFjA+nA4sKpE20/OpSttGdhnG6VqZKXITpkdWXn2Q2xa5PK6NCKnk8aaFcwjUzBx/03RW+ml4LfLTO6hgGGQSruqa1iqwwBNKAfL2Un1balhJjhnBH01zTNLLJm4f2eRP8KDNhi3m3MDu7VKIFdRDvE1ZCtFRyDPEh5xF8GtkCzPkkssFL/Wepq1NYApbPGSZcMApIEzBfjo5epmgFeRc/ODxyFCyf8GyWQA/4Rwg5eUiaC7zokmfnydR9niBrbNVAvYmx20k2Gkxj1B1k5F7H8NP9kfW2OvknuRco2nVUmdHY3iacPe9bSmuGAuft4t7fMNM7YKZNy/bsPvpf2Kry1VPMAm0c8oD2+c37PqEfft4mFbm2DUyhdbdVWFwdFxRkXEH649dcqcF586jtnHlqqG3k0P0aBWYfzddYV4rJN44KmZX9e/72DbShbq8pnlFNizRZleAFRKa6M49nJC9mT8TOOeXipMuFW8qPV0BGphb4GBRFsri2I+ZQw2zMjcWGG4oHm/jA2b219gAI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: sealed-secret-application
    type: Opaque

